stages: 
  data_ingestion:
    cmd: python3 src/eForecaster/pipeline/stage_01_data_ingestion.py
    deps:
      - src/eForecaster/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/data.zip

  training:
    cmd: python3 src/eForecaster/pipeline/stage_02_training.py
    deps: 
      - src/eForecaster/pipeline/stage_02_training.py
      - config/config.yaml
    params: 
      - XGRBoost.BASE_SCORE
      - XGRBoost.BOOSTER
      - XGRBoost.N_ESTIMATORS
      - XGRBoost.EARLY_STOPPING_ROUNDS
      - XGRBoost.OBJECTIVE
      - XGRBoost.MAX_DEPTH
      - XGRBoost.LEARNING_RATE
    outs:
      - artifacts/training/model.joblib

  model_evaluation: 
    cmd: python3 src/eForecaster/pipeline/stage_03_model_evaluation.py
    deps: 
      - src/eForecaster/pipeline/stage_03_model_evaluation.py
      - config/config.yaml
      - artifacts/training/model.joblib
    metrics:
      - artifacts/model_evaluation/metrics.json:
          cache: false

    