
artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/gorogandras/public-data/raw/main/ver_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  csv_name: ver_data.csv

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.joblib
  train_dataset_path: artifacts/data_ingestion/train.csv
  test_dataset_path: artifacts/data_ingestion/test.csv

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_ingestion/test.csv
  train_data_path: artifacts/data_ingestion/train.csv
  model_path: artifacts/training/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

prediction:
  root_dir: artifacts/prediction
  model_path: artifacts/training/model.joblib
  prediction_path: artifacts/prediction
  scatterplot_path: artifacts/prediction/scatterplot.png

plotting: 
  root_dir: artifacts/plotting
  model_path: artifacts/training/model.joblib
  test_data_path: artifacts/data_ingestion/test.csv
  scatterplot_path: artifacts/plotting/scatterplot.png