
artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/gorogandras/public-data/raw/main/ver_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  csv_name: ver_data.csv

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.joblib
  train_dataset_path: artifacts/data_ingestion/train.csv
  test_dataset_path: artifacts/data_ingestion/test.csv

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_ingestion/test.csv
  model_path: artifacts/training/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json